package record

import (
	"fmt"
	"strings"
)

// AnswerTOML returns the contents of the answer.toml file fed to
// proxmox-auto-install-assistant. The schema is documented at:
//
//	https://pve.proxmox.com/pve-docs/chapter-pve-installation.html#unattended_installation
//
// We use static IPv4 addressing so the recorder knows the nested VM's
// address ahead of time. The [first-boot] section points at firstBootURL,
// which is served by the local FileServer during the install/first-boot
// window — this lets us iterate on the seed contract without re-mastering
// the ISO between records.
func AnswerTOML(c *Config, firstBootURL string) string {
	ip := c.NestedIP
	netmask := strings.SplitN(ip, "/", 2)
	cidr := "24"
	if len(netmask) == 2 {
		cidr = netmask[1]
		ip = netmask[0]
	}

	return fmt.Sprintf(`# Generated by go-proxmox/mage/record. Do not edit.
[global]
keyboard = "en-us"
country = "us"
fqdn = "recorder.example.test"
mailto = "mail@example.test"
timezone = "UTC"
root_password = %q
# disable installer reporting; offline-friendly.
reboot_on_error = false

[network]
source = "from-answer"
cidr = "%s/%s"
dns = "1.1.1.1"
gateway = %q
filter.ID_NET_NAME = "*"

[disk-setup]
filesystem = "ext4"
disk_list = ["sda"]

[first-boot]
source = "from-url"
url = %q
ordering = "fully-up"
`, c.NestedRootPassword, ip, cidr, c.NestedGateway, firstBootURL)
}

// FirstBootScript returns the bash script that runs once on first boot of
// the nested PVE. It implements the SEED.md contract: creates the recorder
// user + token, then provisions the pinned VMs and CTs with their indexed
// device configs.
//
// The script is intentionally idempotent (`|| true` on resource creates) so
// that a partial first-boot retry works.
func FirstBootScript(c *Config) string {
	const script = `#!/bin/bash
# go-proxmox recorder seed. Idempotent. Logs to /var/log/go-proxmox-seed.log.
set -e
exec > >(tee -a /var/log/go-proxmox-seed.log) 2>&1
echo "[seed] starting at $(date)"

# 1) recorder user + admin role + API token.
pveum user add recorder@pve --comment "go-proxmox cassette recorder" || true
pveum acl modify / --user recorder@pve --role Administrator || true
pveum user token add recorder@pve cassettes \
  --privsep 0 \
  --value '%[1]s' || true

# 2) Wide-config stopped VM 9003 — exercises issue #211 routing
#    (>9 indices, scsihw vs scsi0 prefix collision, bare numa scalar).
qm create 9003 --name vm-stopped --memory 512 --cores 1 \
  --scsihw virtio-scsi-pci --numa 1 --net0 virtio,bridge=vmbr0 || true
qm set 9003 \
  --scsi0 local-lvm:0,size=8G \
  --scsi30 local-lvm:0,size=8G \
  --net15 virtio,bridge=vmbr0 \
  --net31 virtio,bridge=vmbr0 \
  --hostpci15 0000:0f:00.0 \
  --ipconfig20 ip=192.0.2.20/24 \
  --numa0 cpus=0-1,memory=512 \
  --unused255 local-lvm:vm-9003-unused-255 || true

# 3) Template VM 9001 — pid:null surface (issue #198).
qm create 9001 --name tpl-ubuntu --memory 512 --cores 1 \
  --net0 virtio,bridge=vmbr0 || true
qm template 9001 || true

# 4) Running VM 9002 — non-null pid + tags.
qm create 9002 --name vm-running --memory 512 --cores 1 \
  --tags "production;webserver" \
  --net0 virtio,bridge=vmbr0 \
  --scsihw virtio-scsi-pci \
  --scsi0 local-lvm:1 || true
qm start 9002 || true

# 5) LXC 9101 — running, wide mp/dev config.
pct create 9101 local:vztmpl/$(ls /var/lib/vz/template/cache/*.tar.* 2>/dev/null | head -1) \
  --hostname ct-running --memory 256 --cores 1 \
  --rootfs local-lvm:1 --net0 name=eth0,bridge=vmbr0,ip=dhcp || true
pct set 9101 \
  --mp0 /srv/data,mp=/data \
  --mp42 /srv/forty-two,mp=/forty-two \
  --mp255 /srv/last,mp=/last \
  --dev15 /dev/sdb15 \
  --net20 name=eth20,bridge=vmbr0 \
  --unused100 local-lvm:subvol-9101-unused-100 || true
pct start 9101 || true

# 6) LXC 9102 — stopped, plain.
pct create 9102 local:vztmpl/$(ls /var/lib/vz/template/cache/*.tar.* 2>/dev/null | head -1) \
  --hostname ct-stopped --memory 256 --cores 1 \
  --rootfs local-lvm:1 --net0 name=eth0,bridge=vmbr0,ip=dhcp || true

echo "[seed] complete at $(date)"
touch /var/lib/go-proxmox-seeded
`
	return fmt.Sprintf(script, c.NestedTokenSecret)
}
